version: '3.1'

services:
  url_shortener:
    build:
      context: .
    restart: always
    environment:
      PORT: 3000
      BASE_URL: https://goi.is
    volumes:
      - ./urls:/app/tmp
    networks:
      - apps

networks:
  apps:
    external:
      name: apps
